# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: adverse-media-api

frameworkVersion: "2"

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2

# The `functions` block defines what code to deploy
functions:
  searchCompaniesData:
    handler: handler.searchCompaniesData
    # The `events` block defines how to trigger the handler.getCompanies code
    events:
      - http:
          path: search-companies-data
          method: get
          cors: true
